# Deploy workflow

name: Deploy


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  deploy:

    runs-on: ubuntu-latest

    if: >-
      (
        github.actor == github.event.repository.owner.login
        && contains(github.event.pull_request.labels.*.name, 'deploy')
      )

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: mchirico/gcp-actions@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.OWNER }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud components update --quiet


    # Credentials
    - name: Get and Create Credentials
      run: |
       mkdir -p credentials
       gsutil cp gs://nodesepta/ts-express/credentials/* ./credentials/.
       mkdir -p angular/src/environments
       gsutil cp gs://nodesepta/ts-express/environments/* ./angular/src/environments/.


    # Basic test
    - name: Firebase Emulator
      run: |
        sudo npm install -g firebase-tools



    # Basic test
    - name: firebase emulators
      run: |
        npm install
        firebase emulators:exec  --project 'septapig' 'npm test' --token "${FIREBASE_TOKEN}"
        bash <(curl -s https://codecov.io/bash)
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version


    # ng command for Angular
    - name: ng command for Angular
      run: |
         sudo npm install -g @angular/cli


    # Angular install and test
    - name: Angular install and test
      run: |
         cd angular
         npm install
         ng lint
         npm run test -- --no-watch --code-coverage --no-progress --browsers=ChromeHeadlessCI
         npm run coverage
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}



    # Deploy
    - name: Deploy
      run: |
        make deploy
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


